module.exports = {
  base: {
    name: "base",
    desc: "基础权限",
    apis: [
      "/api/login/login",
      "api/user/userInfo",
      "api/user/logout",
      "api/user/userDetail",
      "api/msg/add",
      "api/msg/getList",
      "api/msg/update",
      "api/msg/del",
    ],
  },
  user: {
    name: "user",
    desc: "用户管理",
    apis: [
      "api/user/userDetail",
      "api/user/userList",
      "api/user/register",
      "api/user/multiAdd",
      "api/user/userChange",
      "api/user/userDel",
    ],
  },

  reservation: {
    name: "reservation",
    desc: "预约管理",
    apis: [
      "/api/reservation/getList",
      "api/reservation/addReservation",
      "api/reservation/modify",
      "api/reservation/del",
      "api/reservationType/add",
      "api/reservationType/getList",
      "api/reservationType/update",
      "api/reservationType/del",
    ],
  },
  exercise: {
    name: "exercise",
    desc: "题库管理",
    apis: [
      "/api/exercise/add",
      "api/exercise/multiAdd",
      "api/exercise/getList",
      "api/exercise/update",
      "api/exercise/del",
      "api/type/getList",
    ],
  },
  paper: {
    name: "paper",
    desc: "试卷管理",
    apis: [
      "/api/paper/add",
      "api/paper/getList",
      "api/paper/detail-score",
      "api/paper/detail",
      "api/paper/update",
      "api/paper/del",
      "api/distribution/add",
      "api/distribution/multiAdd",
      "api/distribution/getList",
      "api/distribution/update",
      "api/distribution/del",
    ],
  },
  record: {
    name: "record",
    desc: "记录管理",
    apis: [
      "/api/record/add",
      "api/record/getUserList",
      "api/record/getRecords",
      "api/record/getOneRecords",
      "api/record/updateTalkRecord",
      "api/record/del",
    ],
  },
  role: {
    name: "role",
    desc: "权限管理",
    apis: ["/api/role/add", "api/role/get", "api/role/update", "api/role/del"],
  },
};
